# TODO: use nix dconf config to import this
[/]
cycle-height-steps=[0.5]
cycle-width-steps=[0.5]
disable-scratch-in-overview=true
drag-drift-speed=10
drift-speed=10
gesture-horizontal-fingers=4
gesture-workspace-fingers=4
horizontal-margin=3
minimap-shade-opacity=156
only-scratch-in-overview=false
open-window-position=0
restore-attach-modal-dialogs='true'
restore-edge-tiling='true'
restore-workspaces-only-on-primary='false'
selection-border-size=5
show-focus-mode-icon=true
show-workspace-indicator=true
vertical-margin=3
vertical-margin-bottom=3
window-gap=3

[keybindings]
barf-out=['']
barf-out-active=['']
center-horizontally=['']
close-window=['<Super>m']
cycle-width=['<Super>p']
drift-left=['']
drift-right=['']
live-alt-tab=['']
live-alt-tab-backward=['']
live-alt-tab-scratch=['']
live-alt-tab-scratch-backward=['']
new-window=['<Super>c']
resize-h-dec=['<Shift><Super>e']
resize-h-inc=['<Shift><Super>n']
resize-w-dec=['<Shift><Super>h']
resize-w-inc=['<Shift><Super>i']
slurp-in=['']
switch-down=['<Super>n']
switch-down-workspace=['<Super>l']
switch-first=['']
switch-focus-mode=['']
switch-global-left=['']
switch-global-right=['']
switch-left=['<Super>h']
switch-monitor-left=['<Super>j']
switch-monitor-right=['<Super>y']
switch-next=['']
switch-open-window-position=['']
switch-previous=['']
switch-right=['<Super>i']
switch-up=['<Super>e']
switch-up-workspace=['<Super>u']
take-window=['<Super>g']
toggle-maximize-width=['<Super>z']
